name: CD Production Workflow 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Login, Build, Push & Deploy on Kubernetes
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: REPLACE_ME

    steps:
    - name: Slack Hook - Start
      uses: act10ns/slack@v1
      with:
        status: starting
        message: "[Prod][Api] Starts Building..."
      if: always()

    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy services in Staging
      uses: ./.github/actions/deploy
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-ecr-repository: gs-go-otv
        aws-eks-region: eu-west-3
        aws-eks-cluster: gs-eks-cluster
        aws-eks-namespace: ciam
        aws-eks-deployments-name: ciam-go-otv

    - name: Slack Hook - End
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        message: "[Prod][Api] Published !"
      if: always()
